### ISSUE TITLE
el-row中改变页面为移动端大小后布局会乱

### ISSUE THREAD

**Issue by LuoMuQ** [Hopetree/hao#53]
![image](https://user-images.githubusercontent.com/63888266/104286163-a198e180-54ef-11eb-9c55-2e87d2d2190a.png)

**解决办法**
在`linkbox.vue`的style中加入
`.el-row {
    display:flex;
    flex-wrap: wrap;
}`

**Comment by Hopetree** [comment]
@LuoMuQ 已修改，哈哈哈，我之前都没把这当回事
